### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by derrgis** [derrgis/ESPJQ6500#3]
Can't compile on ESP01
w/ ARDUINO 1.8.7 IDE
---------------------------------------------
OS10.11.6 (15G22010)
Mac Pro (mi-2010)
Processeur 2 x 2,4 GHz Quad-Core Intel Xeon
Mémoire 8 Go 1066 MHz DDR3 ECC
GPU ATI Radeon HD 5770 1024 Mo
---------------------------------------------
LIB USED :
JQ6500
https://github.com/sleemanj/JQ6500_Serial

SoftwareSerial ESP32/8266
https://github.com/plerup/espsoftwareserial/
---------------------------------------------
CONSOLE ERROR
Arduino: 1.8.7 (Mac OS X), Board: "Generic ESP8266 Module, 80 MHz, Flash, ck, 26 MHz, 40MHz, QIO, 512K (64K SPIFFS), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

WARNING: library JQ6500_Serial-master claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (esp8266) architecture(s).
In file included from /Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:38:0:
/Users/dg/Documents/Arduino/libraries/JQ6500_Serial-master/src/JQ6500_Serial.h: In constructor 'JQ6500_Serial::JQ6500_Serial()':
/Users/dg/Documents/Arduino/libraries/JQ6500_Serial-master/src/JQ6500_Serial.h:112:38: error: no matching function for call to 'SoftwareSerial::SoftwareSerial()'
     JQ6500_Serial() : SoftwareSerial() { };
                                      ^
/Users/dg/Documents/Arduino/libraries/JQ6500_Serial-master/src/JQ6500_Serial.h:112:38: note: candidates are:
In file included from /Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:37:0:
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/SoftwareSerial/SoftwareSerial.h:37:3: note: SoftwareSerial::SoftwareSerial(int, int, bool, unsigned int)
   SoftwareSerial(int receivePin, int transmitPin, bool inverse_logic = false, unsigned int buffSize = 64);

   ^
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/SoftwareSerial/SoftwareSerial.h:37:3: note:   candidate expects 4 arguments, 0 provided
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/SoftwareSerial/SoftwareSerial.h:35:7: note: constexpr SoftwareSerial::SoftwareSerial(const SoftwareSerial&)
 class SoftwareSerial : public Stream {

       ^
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/SoftwareSerial/SoftwareSerial.h:35:7: note:   candidate expects 1 argument, 0 provided
In file included from /Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:57:0:
/Users/dg/Documents/Arduino/libraries/FastLED/FastLED.h: At global scope:
/Users/dg/Documents/Arduino/libraries/FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.006
 #    pragma message "FastLED version 3.002.006"
                     ^
In file included from /Users/dg/Documents/Arduino/libraries/FastLED/FastLED.h:65:0,
                 from /Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:57:
/Users/dg/Documents/Arduino/libraries/FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^
/Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino: In function 'void setup()':
ESPJQ6500:425:21: error: no matching function for call to 'JQ6500_Serial::begin(int, int, int)'
   mp3.begin(9600,3,2);
                     ^
/Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:425:21: note: candidate is:
In file included from /Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:37:0:
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/SoftwareSerial/SoftwareSerial.h:40:8: note: void SoftwareSerial::begin(long int)
   void begin(long speed);

        ^
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/SoftwareSerial/SoftwareSerial.h:40:8: note:   candidate expects 1 argument, 3 provided
ESPJQ6500:451:22: error: no matching function for call to 'MDNSResponder::begin(String&)'
   MDNS.begin(clientID);
                      ^
/Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:451:22: note: candidates are:
In file included from /Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:46:0:
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266mDNS/ESP8266mDNS.h:64:8: note: bool MDNSResponder::begin(const char*)
   bool begin(const char* hostName);
        ^
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266mDNS/ESP8266mDNS.h:64:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266mDNS/ESP8266mDNS.h:66:8: note: bool MDNSResponder::begin(const char*, IPAddress, uint32_t)
   bool begin(const char* hostName, IPAddress ip, uint32_t ttl=120){
        ^
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266mDNS/ESP8266mDNS.h:66:8: note:   candidate expects 3 arguments, 1 provided
Multiple libraries were found for "SoftwareSerial.h"
 Used: /Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/SoftwareSerial
 Not used: /Users/dg/Documents/Arduino/libraries/EspSoftwareSerial
exit status 1
no matching function for call to 'JQ6500_Serial::begin(int, int, int)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Liliputech** [comment]
Voici les instructions que j'avais suivi pour installer mon environnement :
https://arduino-esp8266.readthedocs.io/en/latest/installing.html#instructions-other-os

**Comment by derrgis** [comment]
FROM SCRATCH REINSTALL from master esp8266/arduino
(Can't compile even simple JQ6500 sketch)
CONSOLE: 
fork/exec /Users/dg/Documents/Arduino/hardware/esp8266com/esp8266/tools/python3/python3: no such file or directory
Erreur de compilation pour la carte Generic ESP8266 Module

**Comment by derrgis** [comment]
posts ici:
https://forum.arduino.cc/index.php?topic=636364.0
et ici
https://github.com/esp8266/Arduino/issues/6528

**Comment by Liliputech** [comment]
Excellent, j'espère que les réponses de la communauté te permettrons d'avancer, malheureusement je ne suis pas en mesure de reproduire ton contexte n'ayant pas de matériel Macintosh à ma disposition.
De mon côté je préfère attendre une validation de ta part avant d'avancer plus avant, de peur de ne pas m'orienter dans la bonne direction.
Tiens moi au courant de tes avancées.
Arthur

**Comment by derrgis** [comment]
Voici une des réponses que j'obtiens
[https://github.com/esp8266/Arduino/issues/6528](url)

Je ne comprends pas tout et on me renvoit vers des Mac Builds à cette page
[https://travis-ci.org/esp8266/Arduino/jobs/584763541](url)

Pourrais-tu me dire ce que je peux faire à cet endroit ?

**Comment by derrgis** [comment]
Mettons de côté mon post précédent et tentons une installation sur un Ubuntu tout frais.
