### ISSUE TITLE
still can't compile after adding zip lib espsoftwareserial from Plerup

### ISSUE THREAD

**Issue by derrgis** [derrgis/ESPJQ6500#6]
STEPS:
download zip from
https://github.com/plerup/espsoftwareserial

add to Arduino IDE
Sketch > add lib > add zip > espsoftwareserial-master.zip

Restart IDE

Compile 
-----------------------------------------------------------------------------------------
ATTENTION : la bibliothèque JQ6500_Serial-master prétend être exécutable sur la (ou les) architecture(s) (avr esp8266 esp32) et peut être incompatible avec votre carte actuelle qui s'exécute sur (esp8266).
In file included from /Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:38:0:
/Users/dg/Documents/Arduino/libraries/JQ6500_Serial-master/src/JQ6500_Serial.h: In constructor 'JQ6500_Serial::JQ6500_Serial()':
/Users/dg/Documents/Arduino/libraries/JQ6500_Serial-master/src/JQ6500_Serial.h:112:38: error: no matching function for call to 'SoftwareSerial::SoftwareSerial()'
     JQ6500_Serial() : SoftwareSerial() { };
                                      ^
/Users/dg/Documents/Arduino/libraries/JQ6500_Serial-master/src/JQ6500_Serial.h:112:38: note: candidate is:
In file included from /Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:37:0:
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/SoftwareSerial/src/SoftwareSerial.h:48:2: note: SoftwareSerial::SoftwareSerial(int, int, bool, int, int)
  SoftwareSerial(int receivePin, int transmitPin, bool inverse_logic = false, int bufSize = 64, int isrBufSize = 0);
  ^
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/SoftwareSerial/src/SoftwareSerial.h:48:2: note:   candidate expects 5 arguments, 0 provided
In file included from /Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:57:0:
/Users/dg/Documents/Arduino/libraries/FastLED/FastLED.h: At global scope:
/Users/dg/Documents/Arduino/libraries/FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.003.002
 #    pragma message "FastLED version 3.003.002"
                     ^
In file included from /Users/dg/Documents/Arduino/libraries/FastLED/FastLED.h:65:0,
                 from /Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:57:
/Users/dg/Documents/Arduino/libraries/FastLED/fastspi.h:130:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^
/Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino: In function 'void setup()':
ESPJQ6500:393:21: error: no matching function for call to 'JQ6500_Serial::begin(int, int, int)'
   mp3.begin(9600,3,2);
                     ^
/Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:393:21: note: candidates are:
In file included from /Users/dg/Documents/Github/ESP01-sketch.01/ESPJQ6500/ESPJQ6500.ino:37:0:
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/SoftwareSerial/src/SoftwareSerial.h:52:7: note: bool SoftwareSerial::begin(int32_t)
  bool begin(int32_t baud) {
       ^
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/SoftwareSerial/src/SoftwareSerial.h:52:7: note:   candidate expects 1 argument, 3 provided
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/SoftwareSerial/src/SoftwareSerial.h:55:7: note: bool SoftwareSerial::begin(int32_t, SoftwareSerialConfig)
  bool begin(int32_t baud, SoftwareSerialConfig config);
       ^
/Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/SoftwareSerial/src/SoftwareSerial.h:55:7: note:   candidate expects 2 arguments, 3 provided
Plusieurs bibliothèque trouvées pour "SoftwareSerial.h"
Utilisé : /Users/dg/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/SoftwareSerial
Non utilisé : /Users/dg/Documents/Arduino/libraries/espsoftwareserial-master
exit status 1
no matching function for call to 'JQ6500_Serial::begin(int, int, int)'

**Comment by Liliputech** [comment]
La presence de espsoftwareserial est détectée mais pas prise en compte.
la lib prise en compte est celle fournie par l'environnement (qui ne semble pas être à jour).
doublon du bug précedemment ouvert.
